"""Precognition — the search panel should never open empty. Guess 3 questions
from the current screen + your query history, so one tap runs them.

Fully local and free: score past queries by embedding-similarity to what's on
screen right now, mix in template questions triggered by cheap detectors (a stack
trace -> "Have I seen this error?"; a page with prior versions -> "What changed
here?"). Nothing is generated by a model.
"""

import logging
import re

from . import db, embed

log = logging.getLogger("rewisp")

_STACKTRACE = re.compile(r"traceback|exception|error:|stack trace|\bat [\w.$]+\(", re.I)
_MEETING = re.compile(r"\b(zoom|google meet|meet\.google|teams|webex|join now|meeting)\b", re.I)


def log_query(conn, text: str, app_context: str | None = None) -> None:
    text = (text or "").strip()
    if not text or len(text) > 300:
        return
    try:
        conn.execute(
            "INSERT INTO queries (text, ts, app_context, embedding) VALUES (?, ?, ?, ?)",
            (text, db.utcnow(), app_context, embed.embed(text)))
        conn.commit()
    except Exception:  # noqa: BLE001
        pass


def mark_tapped(conn, text: str) -> None:
    """A suggested question that got tapped — feeds the tap-through score."""
    conn.execute(
        "UPDATE queries SET was_tapped = 1 WHERE text = ? AND ts = "
        "(SELECT MAX(ts) FROM queries WHERE text = ?)", (text, text))
    conn.commit()


def _worth_suggesting(text: str) -> bool:
    """A past query worth re-offering: question-shaped, not a test/typo blip."""
    words = text.split()
    if not 3 <= len(words) <= 14:
        return False
    if text.lower().startswith(("test", "asdf", "http")):
        return False
    return True


def _current_screen(conn) -> tuple[str, str]:
    row = conn.execute(
        "SELECT app, ocr_text FROM captures ORDER BY id DESC LIMIT 1").fetchone()
    return (row[0] or "", row[1] or "") if row else ("", "")


def suggest(conn, limit: int = 3) -> list[str]:
    """Top guessed questions for the current screen. Templates (high intent) first,
    then history ranked by semantic similarity to what's on screen."""
    app, screen = _current_screen(conn)
    out: list[str] = []

    # Template questions from cheap detectors — highest intent.
    if _STACKTRACE.search(screen[:4000]):
        out.append("Have I seen this error before?")
    if _MEETING.search(screen[:4000]):
        out.append("What's the link for this meeting?")
    # A page we have prior versions of -> Delta is available.
    from . import delta
    key = db.latest_page_key(conn)
    if key:
        n = conn.execute("SELECT COUNT(*) FROM captures WHERE page_key=?", (key,)).fetchone()[0]
        if n >= 2:
            out.append("What changed on this page?")

    # History ranked by similarity to the current screen. Two tiers: queries
    # semantically NEAR the screen (sim floor — otherwise a random old Netflix
    # question rides along on every page), then recent queries as padding.
    qvec = embed.embed_vec(screen[:2000]) if screen else None
    recents: list[str] = []
    if qvec is not None:
        import numpy as np
        rows = conn.execute(
            "SELECT text, embedding, was_tapped, ts FROM queries WHERE embedding IS NOT NULL "
            "ORDER BY id DESC LIMIT 200").fetchall()
        scored = []
        seen = {o.lower() for o in out}
        for text, blob, tapped, ts in rows:
            if not text or text.lower() in seen or not _worth_suggesting(text):
                continue
            seen.add(text.lower())
            if len(recents) < 10:
                recents.append(text)
            v = np.frombuffer(blob, dtype=np.float32)
            sim = float(np.asarray(qvec) @ v)
            if sim < 0.25:
                continue                       # unrelated to this screen
            recent = ts >= db.utcnow()[:10]    # asked today
            score = sim + (0.15 if tapped else 0.0) + (0.05 if recent else 0.0)
            scored.append((score, text))
        scored.sort(key=lambda x: -x[0])
        out.extend(text for _s, text in scored[: limit + 2 - len(out)])
        # Pad with recent good queries only if the relevant tier came up short.
        for text in recents:
            if len(out) >= limit:
                break
            if text not in out:
                out.append(text)

    # Fuzzy de-dupe: 'what show was i watching just now?' and '…just now on
    # netflix?' are the same suggestion. Drop a candidate that's a prefix of, or
    # >0.8 similar to, one already kept.
    from difflib import SequenceMatcher
    final: list[str] = []
    for q in out:
        qn = q.rstrip("?. ").lower()
        dup = False
        for k in final:
            kn = k.rstrip("?. ").lower()
            if qn == kn or qn.startswith(kn) or kn.startswith(qn) \
               or SequenceMatcher(None, qn, kn).ratio() > 0.8:
                dup = True
                break
        if not dup:
            final.append(q)
    return final[:limit]
